version: '3.3'
services:
  postgres:
    container_name: 'postgres_db'
    image: 'postgres'
    environment:
      - 'DBUser=comapp'
      - 'DBPASS=123'
    volumes:
      - '~/data/postgresdb:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - 'app-network'
networks:
  app-network:
    driver: 'bridge'